language: go

go:
  - "1.13"

install:
- curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.21.0

script:
- go test ./... -race -coverprofile=coverage.txt -covermode=atomic
- golangci-lint

after_success:
- bash <(curl -s https://codecov.io/bash)
